apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: cdevents-pipelinerun-
spec:
  serviceAccountName: docker-login
  pipelineRef:
    name: cdevents-pipeline
  params:
    - name: IMAGE
      value: docker.io/waveywaves/bookstore
    - name: TAG
      value: tekton-1
  workspaces:
    - name: linked-workspace
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 10Gi